- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Remove default config
  file: 
    name: /etc/nginx/nginx.conf
    state: absent

- name: Configure nginx
  template:
    src: templates/nginx.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - "Restart nginx"

- name: Configure default vhost
  template:
    src: templates/default_site.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - "Restart nginx"

- name: Add home page
  template:
    src: templates/index.j2
    dest: /var/www/html/index.html

- name: Enable and start nginx
  service:
    name: nginx
    enabled: yes
    state: started

- name: Remove packages from cache
  apt:
    autoclean: yes

